# -*- coding: utf-8 -*-
"""02_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16k75plkdqgzqu5UmxD89WT3u79l2BzIX
"""

import sys, os
IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    !pip install -q monai nibabel tqdm


    DATA_DIR = '/content/drive/Othercomputers/My Laptop/BraTS-PEDs-v1/Training'
    OUT_DIR  = '/content/drive/MyDrive/BraTS_PEDs_outputs/eda'
else:
    DATA_DIR = 'data/training'
    OUT_DIR  = 'outputs/eda'

os.makedirs(OUT_DIR, exist_ok=True)
print(f'DATA_DIR: {DATA_DIR}')
print(f'OUT_DIR : {OUT_DIR}')

import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
from tqdm import tqdm

# PEDs uses 5 labels (0-4), different from adult BraTS (0,1,2,4)
MODALITIES = ['t1n', 't1c', 't2w', 't2f']
MOD_TITLES = ['T1 (Native)', 'T1c (Contrast)', 'T2', 'T2-FLAIR']

LABEL_MAP = {
    0: 'Background',
    1: 'Enhancing Tumor (ET)',
    2: 'Non-Enhancing Tumor (NET)',
    3: 'Cystic Component (CC)',
    4: 'Peritumoral Edema (ED)',
}
LABEL_COLORS = {0: 'black', 1: 'red', 2: 'blue', 3: 'cyan', 4: 'yellow'}

def find_files(patient_dir):
    pid = patient_dir.name
    files = {}
    for mod in MODALITIES:
        p = patient_dir / f'{pid}-{mod}.nii.gz'
        files[mod] = p if p.exists() else None
    seg_p = patient_dir / f'{pid}-seg.nii.gz'
    files['seg'] = seg_p if seg_p.exists() else None
    return files

def load_vol(path):
    return nib.load(str(path)).get_fdata().astype(np.float32)

DATA_PATH   = Path(DATA_DIR)
patient_dirs = sorted([d for d in DATA_PATH.iterdir() if d.is_dir()])
print(f'Total patients: {len(patient_dirs)}')

def plot_modalities(patient_dir, save=True):
    files = find_files(patient_dir)
    pid   = patient_dir.name

    fig, axes = plt.subplots(1, 5, figsize=(22, 4))
    fig.suptitle(f'Patient: {pid} — Axial Mid-Slice', fontsize=13, fontweight='bold')

    for i, (mod, title) in enumerate(zip(MODALITIES, MOD_TITLES)):
        vol = load_vol(files[mod])
        sl  = vol[:, :, vol.shape[2]//2].T
        axes[i].imshow(sl, cmap='gray', origin='lower')
        axes[i].set_title(title, fontsize=10)
        axes[i].axis('off')

    # Segmentation overlay on FLAIR
    flair = load_vol(files['t2f'])
    seg   = load_vol(files['seg'])
    mid   = flair.shape[2] // 2
    axes[4].imshow(flair[:, :, mid].T, cmap='gray', origin='lower')
    # Overlay each label with its color
    seg_sl = seg[:, :, mid].T
    cmap_colors = [(0,0,0,0), (1,.1,.1,.7), (.1,.1,1,.7), (0,1,1,.7), (1,1,0,.7)]
    import matplotlib.colors as mcolors
    cmap = mcolors.ListedColormap(cmap_colors)
    axes[4].imshow(seg_sl, cmap=cmap, vmin=0, vmax=4, origin='lower')
    patches = [mpatches.Patch(color=cmap_colors[k], label=LABEL_MAP[k])
               for k in range(1, 5)]
    axes[4].legend(handles=patches, loc='lower right', fontsize=6)
    axes[4].set_title('Segmentation (on FLAIR)', fontsize=10)
    axes[4].axis('off')

    plt.tight_layout()
    if save:
        plt.savefig(f'{OUT_DIR}/{pid}_modalities.png', dpi=150, bbox_inches='tight')
    plt.show(); plt.close()

plot_modalities(patient_dirs[0])
print('Modality plot saved')

def plot_three_planes(patient_dir, modality='t2f', save=True):
    files = find_files(patient_dir)
    pid   = patient_dir.name
    vol   = load_vol(files[modality])
    seg   = load_vol(files['seg'])
    H, W, D = vol.shape

    planes = [
        (vol[:, :, D//2].T,    seg[:, :, D//2].T,    'Axial'),
        (vol[:, W//2, :].T,    seg[:, W//2, :].T,    'Coronal'),
        (vol[H//2, :, :].T,    seg[H//2, :, :].T,    'Sagittal'),
    ]

    import matplotlib.colors as mcolors
    cmap_colors = [(0,0,0,0), (1,.1,.1,.7), (.1,.1,1,.7), (0,1,1,.7), (1,1,0,.7)]
    cmap = mcolors.ListedColormap(cmap_colors)

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle(f'{pid} — T2-FLAIR Three Planes', fontsize=13, fontweight='bold')

    for col, (v, s, name) in enumerate(planes):
        axes[0, col].imshow(v, cmap='gray', origin='lower')
        axes[0, col].set_title(f'{name} — MRI'); axes[0, col].axis('off')

        axes[1, col].imshow(v, cmap='gray', origin='lower')
        masked = np.ma.masked_where(s == 0, s)
        axes[1, col].imshow(masked, cmap=cmap, vmin=0, vmax=4, alpha=0.7, origin='lower')
        axes[1, col].set_title(f'{name} — Overlay'); axes[1, col].axis('off')

    plt.tight_layout()
    if save:
        plt.savefig(f'{OUT_DIR}/{pid}_three_planes.png', dpi=150, bbox_inches='tight')
    plt.show(); plt.close()

plot_three_planes(patient_dirs[0])
print('Three-plane plot saved')

def compute_class_dist(n=50):
    counts = {k: 0 for k in LABEL_MAP}
    for pdir in tqdm(patient_dirs[:n], desc='Computing distribution'):
        files = find_files(pdir)
        if files['seg'] is None: continue
        seg = load_vol(files['seg']).astype(int)
        for label in LABEL_MAP:
            counts[label] += int((seg == label).sum())
    return counts

counts = compute_class_dist(n=50)
total  = sum(counts.values())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('BraTS-PEDs — Voxel Class Distribution', fontsize=13, fontweight='bold')

labels_txt = [LABEL_MAP[k] for k in LABEL_MAP]
pcts       = [counts[k]/total*100 for k in LABEL_MAP]
colors     = ['#333333', '#e74c3c', '#3498db', '#1abc9c', '#f1c40f']

axes[0].bar(range(5), pcts, color=colors, edgecolor='white')
axes[0].set_xticks(range(5))
axes[0].set_xticklabels(['BG', 'ET', 'NET', 'CC', 'ED'], fontsize=9)
axes[0].set_ylabel('% of Total Voxels')
axes[0].set_title('All Classes')
for i, p in enumerate(pcts):
    axes[0].text(i, p+0.1, f'{p:.2f}%', ha='center', fontsize=8)

# Tumor-only pie
tumor_pcts  = [counts[k]/total*100 for k in range(1,5)]
tumor_lbls  = ['ET', 'NET', 'CC', 'ED']
tumor_colors= colors[1:]
axes[1].pie(tumor_pcts, labels=tumor_lbls, autopct='%1.1f%%',
            colors=tumor_colors, startangle=90)
axes[1].set_title('Tumor Sub-regions Only')

plt.tight_layout()
plt.savefig(f'{OUT_DIR}/class_distribution.png', dpi=150, bbox_inches='tight')
plt.show(); plt.close()

print('\nVoxel counts:')
for k, v in counts.items():
    print(f'  {LABEL_MAP[k]:<30}: {v:>12,} ({v/total*100:.3f}%)')

def plot_intensity_dist(patient_dir, save=True):
    files = find_files(patient_dir)
    pid   = patient_dir.name
    fig, axes = plt.subplots(1, 4, figsize=(18, 4))
    fig.suptitle(f'{pid} — Intensity Distributions', fontsize=12)

    for i, (mod, title) in enumerate(zip(MODALITIES, MOD_TITLES)):
        vol = load_vol(files[mod]).flatten()
        nz  = vol[vol > 0]
        axes[i].hist(nz, bins=100, color='steelblue', alpha=0.8, edgecolor='none')
        axes[i].set_title(title)
        axes[i].set_xlabel('Intensity')
        axes[i].set_ylabel('Count' if i==0 else '')
        axes[i].axvline(nz.mean(), color='red', linestyle='--',
                        label=f'μ={nz.mean():.0f}')
        axes[i].legend(fontsize=8)

    plt.tight_layout()
    if save:
        plt.savefig(f'{OUT_DIR}/{pid}_intensities.png', dpi=150, bbox_inches='tight')
    plt.show(); plt.close()

plot_intensity_dist(patient_dirs[0])
print('EDA complete — all plots saved to:', OUT_DIR)

import numpy as np
import torch
from pathlib import Path
from typing import List, Dict
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
import monai.transforms as T
from monai.data import CacheDataset, list_data_collate


MODALITIES   = ['t1n', 't1c', 't2w', 't2f']
IN_CHANNELS  = 4
OUT_CHANNELS = 5   # 0=BG, 1=ET, 2=NET, 3=CC, 4=ED
ROI_SIZE     = (128, 128, 128)
VAL_RATIO    = 0.15
TEST_RATIO   = 0.10
SEED         = 42


print('Constants set. OUT_CHANNELS=5 for PEDs (ET, NET, CC, ED)')

def build_file_list(data_dir: str) -> List[Dict]:
    """
    Scans DATA_DIR for patients that have ALL 4 modalities + seg mask.
    File naming: BraTS-PED-00XXX-000-{mod}.nii.gz
    """
    records = []
    data_path = Path(data_dir)

    for pdir in sorted(data_path.iterdir()):
        if not pdir.is_dir():
            continue
        pid = pdir.name
        entry = {'image': [], 'label': None}


        all_found = True
        for mod in MODALITIES:
            exact = pdir / f'{pid}-{mod}.nii.gz'
            if exact.exists():
                entry['image'].append(str(exact))
            else:

                matches = list(pdir.glob(f'*-{mod}.nii.gz'))
                if matches:
                    entry['image'].append(str(matches[0]))
                else:
                    all_found = False
                    break


        seg_exact = pdir / f'{pid}-seg.nii.gz'
        if seg_exact.exists():
            entry['label'] = str(seg_exact)
        else:
            seg_matches = list(pdir.glob('*-seg.nii.gz'))
            if seg_matches:
                entry['label'] = str(seg_matches[0])

        if all_found and len(entry['image']) == 4 and entry['label']:
            records.append(entry)

    print(f'Valid patients with all modalities + seg: {len(records)}')
    return records


def split_data(records):
    train_val, test = train_test_split(
        records, test_size=TEST_RATIO, random_state=SEED)
    train, val = train_test_split(
        train_val, test_size=VAL_RATIO/(1-TEST_RATIO), random_state=SEED)
    print(f'Split → Train: {len(train)} | Val: {len(val)} | Test: {len(test)}')
    return train, val, test


records = build_file_list(DATA_DIR)
train_files, val_files, test_files = split_data(records)

def get_train_transforms():
    return T.Compose([
        # Load 4 modality paths and stack to (4, H, W, D)
        T.LoadImaged(keys=['image', 'label'], image_only=False),
        T.EnsureChannelFirstd(keys=['image', 'label']),

        # Crop to non-zero brain region
        T.CropForegroundd(keys=['image', 'label'], source_key='image'),

        # Resample to isotropic 1mm³
        T.Spacingd(
            keys=['image', 'label'],
            pixdim=(1.0, 1.0, 1.0),
            mode=('bilinear', 'nearest'),
        ),

        # Z-score normalise per modality (non-zero voxels only)
        T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),

        # Random spatial crop
        T.RandCropByPosNegLabeld(
            keys=['image', 'label'],
            label_key='label',
            spatial_size=ROI_SIZE,
            pos=2,
            neg=1,
            num_samples=1,
        ),

        # Pad if volume is smaller than ROI_SIZE
        T.SpatialPadd(keys=['image', 'label'], spatial_size=ROI_SIZE),


        T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=0),
        T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=1),
        T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=2),
        T.RandRotate90d(keys=['image', 'label'], prob=0.5, max_k=3),
        T.RandScaleIntensityd(keys='image', factors=0.1, prob=0.5),
        T.RandShiftIntensityd(keys='image', offsets=0.1, prob=0.5),
        T.RandGaussianNoised(keys='image', prob=0.2, mean=0.0, std=0.1),
        T.RandGaussianSmoothd(keys='image', prob=0.2),
        T.Rand3DElasticd(
            keys=['image', 'label'],
            prob=0.2,
            sigma_range=(5, 8),
            magnitude_range=(50, 150),
            mode=('bilinear', 'nearest'),
        ),
        T.ToTensord(keys=['image', 'label']),
    ])


def get_val_transforms():
    return T.Compose([
        T.LoadImaged(keys=['image', 'label'], image_only=False),
        T.EnsureChannelFirstd(keys=['image', 'label']),
        T.CropForegroundd(keys=['image', 'label'], source_key='image'),
        T.Spacingd(
            keys=['image', 'label'],
            pixdim=(1.0, 1.0, 1.0),
            mode=('bilinear', 'nearest'),
        ),
        T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
        T.SpatialPadd(keys=['image', 'label'], spatial_size=ROI_SIZE),
        T.ToTensord(keys=['image', 'label']),
    ])

print('Transforms defined.')

def get_dataloaders(train_files, val_files, test_files,
                    batch_size=2, num_workers=2, cache_rate=0.1):
    train_ds = CacheDataset(
        data=train_files,
        transform=get_train_transforms(),
        cache_rate=cache_rate,
        num_workers=num_workers,
    )
    val_ds = CacheDataset(
        data=val_files,
        transform=get_val_transforms(),
        cache_rate=cache_rate,
        num_workers=num_workers,
    )
    test_ds = CacheDataset(
        data=test_files,
        transform=get_val_transforms(),
        cache_rate=0.0,
        num_workers=num_workers,
    )
    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, collate_fn=list_data_collate,
        pin_memory=torch.cuda.is_available(),
    )
    val_loader  = DataLoader(val_ds,  batch_size=1, shuffle=False,
                             num_workers=num_workers, collate_fn=list_data_collate)
    test_loader = DataLoader(test_ds, batch_size=1, shuffle=False,
                             num_workers=num_workers, collate_fn=list_data_collate)
    return train_loader, val_loader, test_loader


print('Building loaders...')
train_loader, val_loader, test_loader = get_dataloaders(
    train_files, val_files, test_files, batch_size=1, num_workers=2
)

batch = next(iter(train_loader))
img, lbl = batch['image'], batch['label']
print(f'Image shape : {img.shape}')
print(f'Label shape : {lbl.shape}')
print(f'Label unique: {lbl.unique()}')
print(f'Image range : [{img.min():.2f}, {img.max():.2f}]')
print('Preprocessing pipeline verified')

import json
lists_path = f'{OUT_DIR}/file_lists.json'
with open(lists_path, 'w') as f:
    json.dump({'train': train_files, 'val': val_files, 'test': test_files}, f)
print(f'File lists saved to: {lists_path}')

import numpy as np
import time, json
from pathlib import Path
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

import monai.transforms as T
from monai.data import CacheDataset, list_data_collate, decollate_batch
from monai.networks.nets import UNet, SegResNet, SwinUNETR
from monai.losses import DiceCELoss
from monai.inferers import sliding_window_inference
from monai.transforms import Activations, AsDiscrete, Compose
from monai.utils import set_determinism

set_determinism(seed=42)
print('Imports done.')

CKPT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs/checkpoints'

CFG = {
    'data_dir':     DATA_DIR,
    'ckpt_dir':     CKPT_DIR,
    'out_dir':      OUT_DIR,


    'model_name':   'unet',
    'in_channels':  4,
    'out_channels': 5,
    'roi_size':     (96, 96, 96),

    # Training
    'epochs':       20,
    'batch_size':   1,
    'lr':           1e-4,
    'weight_decay': 1e-5,
    'num_workers':  4,
    'amp':          True,
    'val_every':    2,
    'cache_rate':   0.05,

    # Sliding window inference
    'sw_batch_size': 2,
    'overlap':       0.5,

    # W&B (optional)
    'use_wandb':    False,
    'project':      'brats-peds-segmentation',
    'run_name':     'unet-peds-baseline',

    # Checkpointing
    'save_top_k':   3,
}
print(json.dumps({k:v for k,v in CFG.items() if k not in ['data_dir','ckpt_dir','out_dir']}, indent=2))

MODALITIES = ['t1n', 't1c', 't2w', 't2f']

def build_file_list(data_dir):
    records = []
    for pdir in sorted(Path(data_dir).iterdir()):
        if not pdir.is_dir(): continue
        pid   = pdir.name
        entry = {'image': [], 'label': None}
        all_found = True
        for mod in MODALITIES:
            p = pdir / f'{pid}-{mod}.nii.gz'
            if not p.exists():
                matches = list(pdir.glob(f'*-{mod}.nii.gz'))
                if matches: p = matches[0]
                else: all_found = False; break
            entry['image'].append(str(p))
        seg = pdir / f'{pid}-seg.nii.gz'
        if not seg.exists():
            matches = list(pdir.glob('*-seg.nii.gz'))
            seg = matches[0] if matches else None
        if all_found and len(entry['image'])==4 and seg:
            entry['label'] = str(seg)
            records.append(entry)
    return records

def get_transforms(train=True):
    base = [
        T.LoadImaged(keys=['image','label'], image_only=False),
        T.EnsureChannelFirstd(keys=['image','label']),
        T.CropForegroundd(keys=['image','label'], source_key='image'),
        T.Spacingd(keys=['image','label'], pixdim=(1.,1.,1.), mode=('bilinear','nearest')),
        T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
    ]
    if train:
        base += [
            T.RandCropByPosNegLabeld(
                keys=['image','label'], label_key='label',
                spatial_size=CFG['roi_size'], pos=2, neg=1, num_samples=1),
            T.SpatialPadd(keys=['image','label'], spatial_size=CFG['roi_size']),
            T.RandFlipd(keys=['image','label'], prob=0.5, spatial_axis=0),
            T.RandFlipd(keys=['image','label'], prob=0.5, spatial_axis=1),
            T.RandFlipd(keys=['image','label'], prob=0.5, spatial_axis=2),
            T.RandRotate90d(keys=['image','label'], prob=0.5, max_k=3),
            T.RandScaleIntensityd(keys='image', factors=0.1, prob=0.5),
            T.RandShiftIntensityd(keys='image', offsets=0.1, prob=0.5),
            T.RandGaussianNoised(keys='image', prob=0.2, std=0.1),
        ]
    else:
        base += [T.SpatialPadd(keys=['image','label'], spatial_size=CFG['roi_size'])]
    base.append(T.ToTensord(keys=['image','label']))
    return T.Compose(base)

records = build_file_list(DATA_DIR)
tr_val, test_f = train_test_split(records, test_size=0.10, random_state=42)
train_f, val_f = train_test_split(tr_val,  test_size=0.15/0.90, random_state=42)
print(f'Train: {len(train_f)} | Val: {len(val_f)} | Test: {len(test_f)}')

train_ds = CacheDataset(train_f, get_transforms(True),  cache_rate=CFG['cache_rate'], num_workers=CFG['num_workers'])
val_ds   = CacheDataset(val_f,   get_transforms(False), cache_rate=CFG['cache_rate'], num_workers=CFG['num_workers'])
test_ds  = CacheDataset(test_f,  get_transforms(False), cache_rate=0.0, num_workers=CFG['num_workers'])

train_loader = DataLoader(train_ds, batch_size=CFG['batch_size'], shuffle=True,
                          num_workers=CFG['num_workers'], collate_fn=list_data_collate,
                          pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=1, shuffle=False,
                          num_workers=CFG['num_workers'], collate_fn=list_data_collate)
test_loader  = DataLoader(test_ds, batch_size=1, shuffle=False,
                          num_workers=CFG['num_workers'], collate_fn=list_data_collate)
print('DataLoaders ready')

import torch
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
def get_model(name, in_ch=4, out_ch=5):
    """out_ch=5 for PEDs (BG + ET + NET + CC + ED)"""
    if name == 'unet':
        return UNet(
            spatial_dims=3, in_channels=in_ch, out_channels=out_ch,
            channels=(32, 64, 128, 256, 512), strides=(2,2,2,2),
            num_res_units=2, norm='BATCH', dropout=0.1,
        )
    elif name == 'segresnet':
        return SegResNet(
            spatial_dims=3, in_channels=in_ch, out_channels=out_ch,
            init_filters=32, blocks_down=(1,2,2,4), blocks_up=(1,1,1),
            dropout_prob=0.1,
        )
    elif name == 'swin_unetr':
        return SwinUNETR(
            img_size=CFG['roi_size'], in_channels=in_ch, out_channels=out_ch,
            feature_size=48, use_checkpoint=True, spatial_dims=3,
        )
    raise ValueError(f'Unknown model: {name}')

model = get_model(CFG['model_name'], CFG['in_channels'], CFG['out_channels']).to(DEVICE)
n_params = sum(p.numel() for p in model.parameters())
print(f'Model: {CFG["model_name"]} | Parameters: {n_params:,}')

# Sanity check
with torch.no_grad():
    dummy = torch.randn(1, 4, 64, 64, 64).to(DEVICE)
    out   = model(dummy)
    print(f'Dummy input: {dummy.shape} → output: {out.shape}')  # (1,5,64,64,64)
del dummy, out; torch.cuda.empty_cache()

loss_fn   = DiceCELoss(to_onehot_y=True, softmax=True,
                       squared_pred=True, smooth_nr=1e-5, smooth_dr=1e-5)
optimizer = torch.optim.AdamW(model.parameters(),
                               lr=CFG['lr'], weight_decay=CFG['weight_decay'])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CFG['epochs'], eta_min=1e-6)
scaler    = torch.cuda.amp.GradScaler(enabled=CFG['amp'])

# Post-processing

post_pred  = Compose([Activations(softmax=True),
                      AsDiscrete(argmax=True, to_onehot=CFG['out_channels'])])
post_label = Compose([AsDiscrete(to_onehot=CFG['out_channels'])])
print('Loss / optimizer / scheduler ready.')

def compute_peds_dice(pred_oh, label_oh):
    def dice(p, l):
        i = (p*l).sum()
        return (2.*i / (p.sum()+l.sum()+1e-5)).item()

    wt_p = ((pred_oh[:,1]+pred_oh[:,2]+pred_oh[:,3]+pred_oh[:,4])>0).float()
    wt_l = ((label_oh[:,1]+label_oh[:,2]+label_oh[:,3]+label_oh[:,4])>0).float()

    tc_p = ((pred_oh[:,1]+pred_oh[:,3])>0).float()
    tc_l = ((label_oh[:,1]+label_oh[:,3])>0).float()

    et_p = pred_oh[:,1].float()
    et_l = label_oh[:,1].float()

    return {'dice_wt': dice(wt_p, wt_l),
            'dice_tc': dice(tc_p, tc_l),
            'dice_et': dice(et_p, et_l)}

print('PEDs region dice function defined. (WT=1+2+3+4, TC=1+3, ET=1)')

class CheckpointManager:
    def __init__(self, ckpt_dir, top_k=3):
        self.dir    = Path(ckpt_dir)
        self.dir.mkdir(parents=True, exist_ok=True)
        self.top_k  = top_k
        self.scores = []

    def save(self, model, optimizer, epoch, metrics):
        score = metrics['dice_mean']
        path  = self.dir / f'epoch{epoch:04d}_dice{score:.4f}.pth'
        torch.save({'epoch': epoch, 'model': model.state_dict(),
                    'optimizer': optimizer.state_dict(), 'metrics': metrics}, path)
        self.scores.append((score, path))
        self.scores.sort(key=lambda x: x[0], reverse=True)
        while len(self.scores) > self.top_k:
            _, old = self.scores.pop()
            if old.exists(): old.unlink()
        return path

    def best(self):
        return self.scores[0] if self.scores else (0.0, None)

ckpt_mgr = CheckpointManager(CKPT_DIR, top_k=CFG['save_top_k'])
print('CheckpointManager ready.')

def train_epoch(model, loader, optimizer, loss_fn, scaler):
    model.train()
    total_loss = 0.0
    for batch in tqdm(loader, desc='  Train', leave=False):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=CFG['amp']):
            preds = model(imgs)
            loss  = loss_fn(preds, labels)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()
        total_loss += loss.item()
    return total_loss / len(loader)


@torch.no_grad()
def validate(model, loader, loss_fn):
    model.eval()
    val_loss = 0.0
    wt_d, tc_d, et_d = [], [], []

    for batch in tqdm(loader, desc='  Val  ', leave=False):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(
            imgs, CFG['roi_size'], CFG['sw_batch_size'], model, overlap=CFG['overlap'])
        val_loss += loss_fn(preds, labels).item()

        preds_post  = [post_pred(p)  for p in decollate_batch(preds)]
        labels_post = [post_label(l) for l in decollate_batch(labels)]
        for p, l in zip(preds_post, labels_post):
            d = compute_peds_dice(p.unsqueeze(0), l.unsqueeze(0))
            wt_d.append(d['dice_wt']); tc_d.append(d['dice_tc']); et_d.append(d['dice_et'])

    return {
        'val_loss':  val_loss / len(loader),
        'dice_wt':   np.mean(wt_d),
        'dice_tc':   np.mean(tc_d),
        'dice_et':   np.mean(et_d),
        'dice_mean': np.mean(wt_d + tc_d + et_d),
    }

print('Training functions defined.')

if CFG['use_wandb']:
    import wandb
    wandb.init(project=CFG['project'], name=CFG['run_name'], config=CFG)

history = {'train_loss':[], 'val_loss':[], 'dice_wt':[], 'dice_tc':[], 'dice_et':[]}
best_dice = 0.0

print(f'Starting training for {CFG["epochs"]} epochs...')
print(f'Model: {CFG["model_name"]} | OUT_CHANNELS: {CFG["out_channels"]} (PEDs 5-class)\n')

for epoch in range(1, CFG['epochs']+1):
    t0 = time.time()

    train_loss = train_epoch(model, train_loader, optimizer, loss_fn, scaler)
    scheduler.step()

    if epoch % CFG['val_every'] == 0 or epoch == 1:
        metrics = validate(model, val_loader, loss_fn)
        elapsed = time.time() - t0

        history['train_loss'].append(train_loss)
        history['val_loss'].append(metrics['val_loss'])
        history['dice_wt'].append(metrics['dice_wt'])
        history['dice_tc'].append(metrics['dice_tc'])
        history['dice_et'].append(metrics['dice_et'])

        print(
            f'Ep {epoch:4d}/{CFG["epochs"]} | '
            f'loss {train_loss:.4f} | '
            f'val {metrics["val_loss"]:.4f} | '
            f'WT {metrics["dice_wt"]:.3f} | '
            f'TC {metrics["dice_tc"]:.3f} | '
            f'ET {metrics["dice_et"]:.3f} | '
            f'mean {metrics["dice_mean"]:.3f} | '
            f'{elapsed:.0f}s'
        )

        if CFG['use_wandb']:
            wandb.log({'epoch': epoch, 'train_loss': train_loss, **metrics})

        if metrics['dice_mean'] > best_dice:
            best_dice = metrics['dice_mean']
            path = ckpt_mgr.save(model, optimizer, epoch, metrics)
            print(f'New best! → {path.name}')

with open(f'{OUT_DIR}/history.json', 'w') as f:
    json.dump(history, f, indent=2)

print(f'\n Done! Best mean Dice: {best_dice:.4f}')
if CFG['use_wandb']: wandb.finish()

import matplotlib.pyplot as plt

epochs_logged = list(range(1, len(history['train_loss'])+1))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('BraTS-PEDs Training History', fontsize=13, fontweight='bold')

axes[0].plot(epochs_logged, history['train_loss'], label='Train', color='#2196F3')
axes[0].plot(epochs_logged, history['val_loss'],   label='Val',   color='#F44336')
axes[0].set_title('Loss'); axes[0].set_xlabel('Epoch'); axes[0].legend(); axes[0].grid(alpha=.3)

axes[1].plot(epochs_logged, history['dice_wt'], label='WT (1+2+3+4)', color='#4CAF50')
axes[1].plot(epochs_logged, history['dice_tc'], label='TC (1+3)',      color='#FF9800')
axes[1].plot(epochs_logged, history['dice_et'], label='ET (1)',        color='#9C27B0')
axes[1].set_title('Dice per Region'); axes[1].set_xlabel('Epoch')
axes[1].set_ylim(0, 1); axes[1].legend(); axes[1].grid(alpha=.3)

plt.tight_layout()
plt.savefig(f'{OUT_DIR}/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

import sys, os
IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    !pip install -q monai nibabel tqdm

    DATA_DIR = '/content/drive/Othercomputers/My Laptop/BraTS-PEDs-v1/Training'
    CKPT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs/checkpoints'
    OUT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs'
else:
    DATA_DIR = 'data/training'
    CKPT_DIR = 'checkpoints'
    OUT_DIR  = 'outputs/eda'

os.makedirs(OUT_DIR, exist_ok=True)
print(f'DATA_DIR: {DATA_DIR}')
print(f'OUT_DIR : {OUT_DIR}')


import torch
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from pathlib import Path
from tqdm import tqdm
from scipy.ndimage import distance_transform_edt

from monai.inferers import sliding_window_inference
from monai.transforms import Activations, AsDiscrete, Compose
from monai.data import decollate_batch
from monai.networks.nets import UNet

OUT_CHANNELS = 5
ROI_SIZE     = (128, 128, 128)
SW_BATCH     = 2
OVERLAP      = 0.5


LABEL_MAP = {0:'Background', 1:'Enhancing Tumor (ET)',
             2:'Non-Enhancing (NET)', 3:'Cystic Component (CC)', 4:'Edema (ED)'}

post_pred  = Compose([Activations(softmax=True),
                      AsDiscrete(argmax=True, to_onehot=OUT_CHANNELS)])
post_label = Compose([AsDiscrete(to_onehot=OUT_CHANNELS)])
print('Imports done.')

def load_best_checkpoint(ckpt_dir):
    ckpts = sorted(Path(ckpt_dir).glob('*.pth'))
    if not ckpts:
        raise FileNotFoundError(f'No checkpoints in {ckpt_dir}')

    best = sorted(ckpts, key=lambda p: float(p.stem.split('dice')[-1]))[-1]
    print(f'Loading: {best.name}')
    return best

model = UNet(
    spatial_dims=3, in_channels=4, out_channels=OUT_CHANNELS,
    channels=(32,64,128,256,512), strides=(2,2,2,2),
    num_res_units=2, norm='BATCH', dropout=0.1,
).to(DEVICE)

ckpt_path = load_best_checkpoint(CKPT_DIR)
ckpt = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
model.load_state_dict(ckpt['model'])
model.eval()
print(f'Loaded from epoch {ckpt["epoch"]} | metrics: {ckpt["metrics"]}')

def dice_score(p, l, eps=1e-5):
    return (2.*(p*l).sum() / (p.sum()+l.sum()+eps)).item()

def hausdorff_95(pred_np, label_np):
    if not pred_np.any() and not label_np.any(): return 0.0
    if not pred_np.any() or not label_np.any():  return np.inf
    d1 = distance_transform_edt(~pred_np)[label_np]
    d2 = distance_transform_edt(~label_np)[pred_np]
    return float(np.percentile(np.concatenate([d1, d2]), 95))

def sens_spec(p, l):
    tp = int((p*l).sum())
    fp = int((p*(1-l)).sum())
    fn = int(((1-p)*l).sum())
    tn = int(((1-p)*(1-l)).sum())
    return tp/(tp+fn+1e-8), tn/(tn+fp+1e-8)

def extract_peds_regions(oh):
    """oh: (B,5,H,W,D) one-hot → WT, TC, ET binary masks"""
    wt = ((oh[:,1]+oh[:,2]+oh[:,3]+oh[:,4])>0).float().unsqueeze(1)
    tc = ((oh[:,1]+oh[:,3])>0).float().unsqueeze(1)
    et = oh[:,1].float().unsqueeze(1)
    return wt, tc, et

print('Metric functions defined.')

import monai.transforms as T
from monai.data import CacheDataset, list_data_collate
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split

MODALITIES = ['t1n','t1c','t2w','t2f']

def build_file_list(data_dir):
    records = []
    for pdir in sorted(Path(data_dir).iterdir()):
        if not pdir.is_dir(): continue
        pid = pdir.name
        entry = {'image':[], 'label':None}
        ok = True
        for mod in MODALITIES:
            p = pdir / f'{pid}-{mod}.nii.gz'
            if not p.exists():
                m = list(pdir.glob(f'*-{mod}.nii.gz'))
                if m: p = m[0]
                else: ok=False; break
            entry['image'].append(str(p))
        seg = pdir / f'{pid}-seg.nii.gz'
        if not seg.exists():
            m = list(pdir.glob('*-seg.nii.gz'))
            seg = m[0] if m else None
        if ok and len(entry['image'])==4 and seg:
            entry['label'] = str(seg)
            records.append(entry)
    return records

val_tfm = T.Compose([
    T.LoadImaged(keys=['image','label'], image_only=False),
    T.EnsureChannelFirstd(keys=['image','label']),
    T.CropForegroundd(keys=['image','label'], source_key='image'),
    T.Spacingd(keys=['image','label'], pixdim=(1.,1.,1.), mode=('bilinear','nearest')),
    T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
    T.SpatialPadd(keys=['image','label'], spatial_size=ROI_SIZE),
    T.ToTensord(keys=['image','label']),
])

records = build_file_list(DATA_DIR)
tr_val, test_f = train_test_split(records, test_size=0.10, random_state=42)
test_ds     = CacheDataset(test_f, val_tfm, cache_rate=0.0, num_workers=2)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False,
                         num_workers=2, collate_fn=list_data_collate)
print(f'Test patients: {len(test_f)}')

@torch.no_grad()
def evaluate(model, loader):
    rows = []
    for i, batch in enumerate(tqdm(loader, desc='Evaluating')):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(imgs, ROI_SIZE, SW_BATCH, model, overlap=OVERLAP)

        for p, l in zip([post_pred(x)  for x in decollate_batch(preds)],
                        [post_label(x) for x in decollate_batch(labels)]):
            p, l = p.unsqueeze(0), l.unsqueeze(0)
            pw, pt, pe = extract_peds_regions(p)
            lw, lt, le = extract_peds_regions(l)

            row = {'sample': i}
            for tag, pp, ll in [('wt',pw,lw),('tc',pt,lt),('et',pe,le)]:
                pn = pp.squeeze().cpu().numpy().astype(bool)
                ln = ll.squeeze().cpu().numpy().astype(bool)
                row[f'dice_{tag}'] = dice_score(
                    torch.from_numpy(pn.astype(np.float32)),
                    torch.from_numpy(ln.astype(np.float32)))
                row[f'hd95_{tag}'] = hausdorff_95(pn, ln)
                s, sp = sens_spec(pn.astype(float), ln.astype(float))
                row[f'sens_{tag}'] = s; row[f'spec_{tag}'] = sp
            rows.append(row)
    return pd.DataFrame(rows)

df = evaluate(model, test_loader)
df.to_csv(f'{OUT_DIR}/evaluation/results.csv', index=False)


print('\n' + '='*60)
print('BRATS-PEDs EVALUATION SUMMARY')
print('='*60)
for region, name in [('wt','Whole Tumor'),('tc','Tumor Core'),('et','Enhancing Tumor')]:
    print(f'\n  {name}:')
    print(f'    Dice : {df[f"dice_{region}"].mean():.4f} ± {df[f"dice_{region}"].std():.4f}')
    print(f'    HD95 : {df[f"hd95_{region}"].mean():.2f} mm')
    print(f'    Sens : {df[f"sens_{region}"].mean():.4f}')
    print(f'    Spec : {df[f"spec_{region}"].mean():.4f}')

import matplotlib.colors as mcolors

CMAP_COLORS = [(0,0,0,0),(1,.1,.1,.7),(.1,.1,1,.7),(0,1,1,.7),(1,1,0,.7)]
PED_CMAP    = mcolors.ListedColormap(CMAP_COLORS)

@torch.no_grad()
def visualise(model, loader, n=3):
    model.eval()
    for i, batch in enumerate(loader):
        if i >= n: break
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(imgs, ROI_SIZE, SW_BATCH, model, overlap=OVERLAP)

        pred_seg  = preds.argmax(1).squeeze().cpu().numpy()
        label_seg = labels.squeeze().cpu().numpy()
        flair     = imgs[0,3].cpu().numpy()     # T2-FLAIR channel

        mid = flair.shape[2]//2
        f_sl, p_sl, l_sl = flair[:,:,mid].T, pred_seg[:,:,mid].T, label_seg[:,:,mid].T

        fig, axes = plt.subplots(1,3, figsize=(15,5))
        fig.suptitle(f'Patient {i+1} — Axial Mid-Slice (T2-FLAIR)', fontsize=12)

        axes[0].imshow(f_sl, cmap='gray', origin='lower')
        axes[0].set_title('FLAIR Input')

        axes[1].imshow(f_sl, cmap='gray', origin='lower')
        axes[1].imshow(np.ma.masked_where(l_sl==0,l_sl),
                       cmap=PED_CMAP, vmin=0, vmax=4, alpha=0.7, origin='lower')
        axes[1].set_title('Ground Truth')

        axes[2].imshow(f_sl, cmap='gray', origin='lower')
        axes[2].imshow(np.ma.masked_where(p_sl==0,p_sl),
                       cmap=PED_CMAP, vmin=0, vmax=4, alpha=0.7, origin='lower')
        axes[2].set_title('Prediction')

        for ax in axes: ax.axis('off')

        # Legend
        from matplotlib.patches import Patch
        patches = [Patch(color=CMAP_COLORS[k][:3], label=LABEL_MAP[k], alpha=0.8)
                   for k in range(1,5)]
        axes[2].legend(handles=patches, loc='lower right', fontsize=7)

        plt.tight_layout()
        plt.savefig(f'{OUT_DIR}/evaluation/pred_sample_{i+1}.png', dpi=150, bbox_inches='tight')
        plt.show(); plt.close()

visualise(model, test_loader, n=3)
print('Visualisations saved')

import sys, os, json, time
from pathlib import Path
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

!pip install -q 'monai[all]==1.3.0' nibabel tqdm scikit-learn

import torch
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')
print(f'GPU   : {torch.cuda.get_device_name(0)}')
print(f'VRAM  : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')

DATA_DIR = '/content/drive/Othercomputers/My Laptop/BraTS-PEDs-v1/Training'
CKPT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs/checkpoints'
OUT_DIR  = '/content/drive/MyDrive/BraTS_PEDs_outputs'

os.makedirs(CKPT_DIR, exist_ok=True)
os.makedirs(OUT_DIR,  exist_ok=True)

CFG = {
    'model_name':    'unet',
    'in_channels':   4,
    'out_channels':  5,
    'roi_size':      (96, 96, 96),    # reduced from 128 for speed

    'epochs':        30,              # total target — will resume from 17
    'batch_size':    1,
    'lr':            1e-4,
    'weight_decay':  1e-5,
    'num_workers':   2,
    'amp':           True,
    'val_every':     2,
    'cache_rate':    0.05,             # increased for faster epochs

    'sw_batch_size': 2,
    'overlap':       0.5,

    'use_wandb':     False,
    'save_top_k':    3,
}

print(json.dumps({k: v for k, v in CFG.items()
                  if k not in ['model_name']}, indent=2))

import sys
if 'monai' not in sys.modules:
    !pip install -q monai nibabel tqdm scikit-learn

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from tqdm import tqdm

import monai.transforms as T
from monai.data import CacheDataset, list_data_collate, decollate_batch
from monai.networks.nets import UNet
from monai.losses import DiceCELoss
from monai.inferers import sliding_window_inference
from monai.transforms import Activations, AsDiscrete, Compose
from monai.utils import set_determinism

set_determinism(seed=42)
print('Imports done.')

MODALITIES = ['t1n', 't1c', 't2w', 't2f']

def build_file_list(data_dir):
    records = []
    for pdir in sorted(Path(data_dir).iterdir()):
        if not pdir.is_dir(): continue
        pid   = pdir.name
        entry = {'image': [], 'label': None}
        ok    = True
        for mod in MODALITIES:
            p = pdir / f'{pid}-{mod}.nii.gz'
            if not p.exists():
                m = list(pdir.glob(f'*-{mod}.nii.gz'))
                if m: p = m[0]
                else: ok = False; break
            entry['image'].append(str(p))
        seg = pdir / f'{pid}-seg.nii.gz'
        if not seg.exists():
            m = list(pdir.glob('*-seg.nii.gz'))
            seg = m[0] if m else None
        if ok and len(entry['image']) == 4 and seg:
            entry['label'] = str(seg)
            records.append(entry)
    print(f'Total patients found: {len(records)}')
    return records

records = build_file_list(DATA_DIR)
tr_val, test_f = train_test_split(records, test_size=0.10, random_state=42)
train_f, val_f = train_test_split(tr_val,  test_size=0.15/0.90, random_state=42)
print(f'Train: {len(train_f)} | Val: {len(val_f)} | Test: {len(test_f)}')

def get_transforms(train=True):
    base = [
        T.LoadImaged(keys=['image', 'label'], image_only=False),
        T.EnsureChannelFirstd(keys=['image', 'label']),
        T.CropForegroundd(keys=['image', 'label'], source_key='image'),
        T.Spacingd(keys=['image', 'label'],
                   pixdim=(1., 1., 1.),
                   mode=('bilinear', 'nearest')),
        T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
    ]
    if train:
        base += [
            T.RandCropByPosNegLabeld(
                keys=['image', 'label'], label_key='label',
                spatial_size=CFG['roi_size'],
                pos=2, neg=1, num_samples=1),
            T.SpatialPadd(keys=['image', 'label'],
                          spatial_size=CFG['roi_size']),
            T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=0),
            T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=1),
            T.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=2),
            T.RandRotate90d(keys=['image', 'label'], prob=0.5, max_k=3),
            T.RandScaleIntensityd(keys='image', factors=0.1, prob=0.5),
            T.RandShiftIntensityd(keys='image', offsets=0.1, prob=0.5),
            T.RandGaussianNoised(keys='image', prob=0.2, std=0.1),
        ]
    else:
        base += [T.SpatialPadd(keys=['image', 'label'],
                               spatial_size=CFG['roi_size'])]
    base.append(T.ToTensord(keys=['image', 'label']))
    return T.Compose(base)


print('Building datasets (caching 50% — first run will be slow)...')
train_ds = CacheDataset(train_f, get_transforms(True),
                        cache_rate=CFG['cache_rate'],
                        num_workers=CFG['num_workers'])
val_ds   = CacheDataset(val_f,   get_transforms(False),
                        cache_rate=CFG['cache_rate'],
                        num_workers=CFG['num_workers'])

train_loader = DataLoader(train_ds, batch_size=CFG['batch_size'],
                          shuffle=True, num_workers=CFG['num_workers'],
                          collate_fn=list_data_collate, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=1, shuffle=False,
                          num_workers=CFG['num_workers'],
                          collate_fn=list_data_collate)
print('DataLoaders ready')

model = UNet(
    spatial_dims=3,
    in_channels=CFG['in_channels'],
    out_channels=CFG['out_channels'],
    channels=(32, 64, 128, 256, 512),
    strides=(2, 2, 2, 2),
    num_res_units=2,
    norm='BATCH',
    dropout=0.1,
).to(DEVICE)

loss_fn   = DiceCELoss(to_onehot_y=True, softmax=True,
                       squared_pred=True, smooth_nr=1e-5, smooth_dr=1e-5)
optimizer = torch.optim.AdamW(model.parameters(),
                              lr=CFG['lr'],
                              weight_decay=CFG['weight_decay'])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CFG['epochs'], eta_min=1e-6)
scaler    = torch.cuda.amp.GradScaler(enabled=CFG['amp'])

post_pred  = Compose([Activations(softmax=True),
                      AsDiscrete(argmax=True,
                                 to_onehot=CFG['out_channels'])])
post_label = Compose([AsDiscrete(to_onehot=CFG['out_channels'])])

print(f'Model parameters: {sum(p.numel() for p in model.parameters()):,}')

class CheckpointManager:
    def __init__(self, ckpt_dir, top_k=3):
        self.dir    = Path(ckpt_dir)
        self.dir.mkdir(parents=True, exist_ok=True)
        self.top_k  = top_k
        self.scores = []

        # Load existing checkpoints into memory so top-k tracking works
        for p in sorted(self.dir.glob('*.pth')):
            try:
                score = float(p.stem.split('dice')[-1])
                self.scores.append((score, p))
            except:
                pass
        self.scores.sort(key=lambda x: x[0], reverse=True)
        print(f'CheckpointManager: found {len(self.scores)} existing checkpoints')

    def save(self, model, optimizer, epoch, metrics):
        score = metrics['dice_mean']
        path  = self.dir / f'epoch{epoch:04d}_dice{score:.4f}.pth'
        torch.save({
            'epoch':     epoch,
            'model':     model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'metrics':   metrics,
        }, path)
        self.scores.append((score, path))
        self.scores.sort(key=lambda x: x[0], reverse=True)
        while len(self.scores) > self.top_k:
            _, old = self.scores.pop()
            if old.exists(): old.unlink()
        return path

    def best(self):
        return self.scores[0] if self.scores else (0.0, None)


def compute_peds_dice(pred_oh, label_oh):
    def dice(p, l):
        i = (p * l).sum()
        return (2. * i / (p.sum() + l.sum() + 1e-5)).item()

    wt_p = ((pred_oh[:,1]+pred_oh[:,2]+pred_oh[:,3]+pred_oh[:,4])>0).float()
    wt_l = ((label_oh[:,1]+label_oh[:,2]+label_oh[:,3]+label_oh[:,4])>0).float()
    tc_p = ((pred_oh[:,1]+pred_oh[:,3])>0).float()
    tc_l = ((label_oh[:,1]+label_oh[:,3])>0).float()
    et_p = pred_oh[:,1].float()
    et_l = label_oh[:,1].float()

    return {
        'dice_wt': dice(wt_p, wt_l),
        'dice_tc': dice(tc_p, tc_l),
        'dice_et': dice(et_p, et_l),
    }

ckpt_mgr = CheckpointManager(CKPT_DIR, top_k=CFG['save_top_k'])
print('Ready')

def train_epoch(model, loader, optimizer, loss_fn, scaler):
    model.train()
    total_loss = 0.0
    for batch in tqdm(loader, desc='  Train', leave=False):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=CFG['amp']):
            loss = loss_fn(model(imgs), labels)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()
        total_loss += loss.item()
    return total_loss / len(loader)


@torch.no_grad()
def validate(model, loader, loss_fn):
    model.eval()
    val_loss, wt_d, tc_d, et_d = 0.0, [], [], []
    for batch in tqdm(loader, desc='  Val  ', leave=False):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(
            imgs, CFG['roi_size'], CFG['sw_batch_size'],
            model, overlap=CFG['overlap'])
        val_loss += loss_fn(preds, labels).item()
        for p, l in zip([post_pred(x) for x in decollate_batch(preds)],
                        [post_label(x) for x in decollate_batch(labels)]):
            d = compute_peds_dice(p.unsqueeze(0), l.unsqueeze(0))
            wt_d.append(d['dice_wt'])
            tc_d.append(d['dice_tc'])
            et_d.append(d['dice_et'])
    return {
        'val_loss':  val_loss / len(loader),
        'dice_wt':   np.mean(wt_d),
        'dice_tc':   np.mean(tc_d),
        'dice_et':   np.mean(et_d),
        'dice_mean': np.mean(wt_d + tc_d + et_d),
    }

print('Train/Val functions defined')

ckpt_files = sorted(Path(CKPT_DIR).glob('*.pth'))
if not ckpt_files:
    raise FileNotFoundError(f'No checkpoints found in {CKPT_DIR}')

best_ckpt = sorted(
    ckpt_files,
    key=lambda p: float(p.stem.split('dice')[-1]))[-1]

print(f'Loading: {best_ckpt.name}')
ckpt = torch.load(best_ckpt, map_location=DEVICE, weights_only=False)
model.load_state_dict(ckpt['model'])
optimizer.load_state_dict(ckpt['optimizer'])

start_epoch = ckpt['epoch'] + 1
best_dice   = ckpt['metrics']['dice_mean']

print(f'Resuming from epoch : {start_epoch}')
print(f'Best dice so far    : {best_dice:.4f}')
print(f'WT / TC / ET        : '
      f'{ckpt["metrics"]["dice_wt"]:.3f} / '
      f'{ckpt["metrics"]["dice_tc"]:.3f} / '
      f'{ckpt["metrics"]["dice_et"]:.3f}')


for _ in range(ckpt['epoch']):
    scheduler.step()

history = {'train_loss': [], 'val_loss': [],
           'dice_wt': [],    'dice_tc': [], 'dice_et': []}

print(f'\n Ready to resume training from epoch {start_epoch} to {CFG["epochs"]}')

PATIENCE    = 10
no_improve  = 0

print(f'Training epochs {start_epoch} → {CFG["epochs"]}')
print(f'Model : {CFG["model_name"]} | roi_size: {CFG["roi_size"]}\n')

for epoch in range(start_epoch, CFG['epochs'] + 1):
    t0         = time.time()
    train_loss = train_epoch(model, train_loader, optimizer, loss_fn, scaler)
    scheduler.step()

    if epoch % CFG['val_every'] == 0 or epoch == start_epoch:
        metrics = validate(model, val_loader, loss_fn)
        elapsed = time.time() - t0

        history['train_loss'].append(train_loss)
        history['val_loss'].append(metrics['val_loss'])
        history['dice_wt'].append(metrics['dice_wt'])
        history['dice_tc'].append(metrics['dice_tc'])
        history['dice_et'].append(metrics['dice_et'])

        print(
            f"Ep {epoch:4d}/{CFG['epochs']} | "
            f"loss {train_loss:.4f} | "
            f"val {metrics['val_loss']:.4f} | "
            f"WT {metrics['dice_wt']:.3f} | "
            f"TC {metrics['dice_tc']:.3f} | "
            f"ET {metrics['dice_et']:.3f} | "
            f"mean {metrics['dice_mean']:.3f} | "
            f"{elapsed:.0f}s"
        )

        if metrics['dice_mean'] > best_dice:
            best_dice  = metrics['dice_mean']
            no_improve = 0
            path = ckpt_mgr.save(model, optimizer, epoch, metrics)
            print(f'New best! → {path.name}')
        else:
            no_improve += 1
            print(f'  No improvement ({no_improve}/{PATIENCE})')
            if no_improve >= PATIENCE:
                print(f'\n Early stopping at epoch {epoch}')
                break

# Save history
history_path = f'{OUT_DIR}/history_resumed.json'
with open(history_path, 'w') as f:
    json.dump(history, f, indent=2)

print(f'\n Done! Best mean Dice: {best_dice:.4f}')
print(f'History saved to: {history_path}')

import matplotlib.pyplot as plt

epochs_logged = list(range(start_epoch,
                           start_epoch + len(history['train_loss'])))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle(f'BraTS-PEDs — Resumed Training (ep {start_epoch}→{epoch})',
             fontsize=13, fontweight='bold')

axes[0].plot(epochs_logged, history['train_loss'], label='Train', color='#2196F3')
axes[0].plot(epochs_logged, history['val_loss'],   label='Val',   color='#F44336')
axes[0].set_title('Loss'); axes[0].set_xlabel('Epoch')
axes[0].legend(); axes[0].grid(alpha=.3)

axes[1].plot(epochs_logged, history['dice_wt'],
             label='WT (1+2+3+4)', color='#4CAF50')
axes[1].plot(epochs_logged, history['dice_tc'],
             label='TC (1+3)',      color='#FF9800')
axes[1].plot(epochs_logged, history['dice_et'],
             label='ET (1)',        color='#9C27B0')
axes[1].set_title('Dice per Region'); axes[1].set_xlabel('Epoch')
axes[1].set_ylim(0, 1); axes[1].legend(); axes[1].grid(alpha=.3)

plt.tight_layout()
plt.savefig(f'{OUT_DIR}/training_curves_resumed.png',
            dpi=150, bbox_inches='tight')
plt.show()
print(f'Saved to: {OUT_DIR}/training_curves_resumed.png')

import sys, os
IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    !pip install -q monai nibabel tqdm

    DATA_DIR = '/content/drive/Othercomputers/My Laptop/BraTS-PEDs-v1/Training'
    CKPT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs/checkpoints'
    OUT_DIR = '/content/drive/MyDrive/BraTS_PEDs_outputs'
else:
    DATA_DIR = 'data/training'
    CKPT_DIR = 'checkpoints'
    OUT_DIR  = 'outputs/eda'

os.makedirs(OUT_DIR, exist_ok=True)
print(f'DATA_DIR: {DATA_DIR}')
print(f'OUT_DIR : {OUT_DIR}')


import torch
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from pathlib import Path
from tqdm import tqdm
from scipy.ndimage import distance_transform_edt

from monai.inferers import sliding_window_inference
from monai.transforms import Activations, AsDiscrete, Compose
from monai.data import decollate_batch
from monai.networks.nets import UNet

OUT_CHANNELS = 5
ROI_SIZE     = (128, 128, 128)
SW_BATCH     = 2
OVERLAP      = 0.5


LABEL_MAP = {0:'Background', 1:'Enhancing Tumor (ET)',
             2:'Non-Enhancing (NET)', 3:'Cystic Component (CC)', 4:'Edema (ED)'}

post_pred  = Compose([Activations(softmax=True),
                      AsDiscrete(argmax=True, to_onehot=OUT_CHANNELS)])
post_label = Compose([AsDiscrete(to_onehot=OUT_CHANNELS)])
print('Imports done.')

def load_best_checkpoint(ckpt_dir):
    ckpts = sorted(Path(ckpt_dir).glob('*.pth'))
    if not ckpts:
        raise FileNotFoundError(f'No checkpoints in {ckpt_dir}')

    best = sorted(ckpts, key=lambda p: float(p.stem.split('dice')[-1]))[-1]
    print(f'Loading: {best.name}')
    return best

model = UNet(
    spatial_dims=3, in_channels=4, out_channels=OUT_CHANNELS,
    channels=(32,64,128,256,512), strides=(2,2,2,2),
    num_res_units=2, norm='BATCH', dropout=0.1,
).to(DEVICE)

ckpt_path = load_best_checkpoint(CKPT_DIR)
ckpt = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
model.load_state_dict(ckpt['model'])
model.eval()
print(f'Loaded from epoch {ckpt["epoch"]} | metrics: {ckpt["metrics"]}')

def dice_score(p, l, eps=1e-5):
    return (2.*(p*l).sum() / (p.sum()+l.sum()+eps)).item()

def hausdorff_95(pred_np, label_np):
    if not pred_np.any() and not label_np.any(): return 0.0
    if not pred_np.any() or not label_np.any():  return np.inf
    d1 = distance_transform_edt(~pred_np)[label_np]
    d2 = distance_transform_edt(~label_np)[pred_np]
    return float(np.percentile(np.concatenate([d1, d2]), 95))

def sens_spec(p, l):
    tp = int((p*l).sum())
    fp = int((p*(1-l)).sum())
    fn = int(((1-p)*l).sum())
    tn = int(((1-p)*(1-l)).sum())
    return tp/(tp+fn+1e-8), tn/(tn+fp+1e-8)

def extract_peds_regions(oh):
    """oh: (B,5,H,W,D) one-hot → WT, TC, ET binary masks"""
    wt = ((oh[:,1]+oh[:,2]+oh[:,3]+oh[:,4])>0).float().unsqueeze(1)
    tc = ((oh[:,1]+oh[:,3])>0).float().unsqueeze(1)
    et = oh[:,1].float().unsqueeze(1)
    return wt, tc, et

print('Metric functions defined.')

import monai.transforms as T
from monai.data import CacheDataset, list_data_collate
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split

MODALITIES = ['t1n','t1c','t2w','t2f']

def build_file_list(data_dir):
    records = []
    for pdir in sorted(Path(data_dir).iterdir()):
        if not pdir.is_dir(): continue
        pid = pdir.name
        entry = {'image':[], 'label':None}
        ok = True
        for mod in MODALITIES:
            p = pdir / f'{pid}-{mod}.nii.gz'
            if not p.exists():
                m = list(pdir.glob(f'*-{mod}.nii.gz'))
                if m: p = m[0]
                else: ok=False; break
            entry['image'].append(str(p))
        seg = pdir / f'{pid}-seg.nii.gz'
        if not seg.exists():
            m = list(pdir.glob('*-seg.nii.gz'))
            seg = m[0] if m else None
        if ok and len(entry['image'])==4 and seg:
            entry['label'] = str(seg)
            records.append(entry)
    return records

val_tfm = T.Compose([
    T.LoadImaged(keys=['image','label'], image_only=False),
    T.EnsureChannelFirstd(keys=['image','label']),
    T.CropForegroundd(keys=['image','label'], source_key='image'),
    T.Spacingd(keys=['image','label'], pixdim=(1.,1.,1.), mode=('bilinear','nearest')),
    T.NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
    T.SpatialPadd(keys=['image','label'], spatial_size=ROI_SIZE),
    T.ToTensord(keys=['image','label']),
])

records = build_file_list(DATA_DIR)
tr_val, test_f = train_test_split(records, test_size=0.10, random_state=42)
test_ds     = CacheDataset(test_f, val_tfm, cache_rate=0.0, num_workers=2)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False,
                         num_workers=2, collate_fn=list_data_collate)
print(f'Test patients: {len(test_f)}')

@torch.no_grad()
def evaluate(model, loader):
    rows = []
    for i, batch in enumerate(tqdm(loader, desc='Evaluating')):
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(imgs, ROI_SIZE, SW_BATCH, model, overlap=OVERLAP)

        for p, l in zip([post_pred(x)  for x in decollate_batch(preds)],
                        [post_label(x) for x in decollate_batch(labels)]):
            p, l = p.unsqueeze(0), l.unsqueeze(0)
            pw, pt, pe = extract_peds_regions(p)
            lw, lt, le = extract_peds_regions(l)

            row = {'sample': i}
            for tag, pp, ll in [('wt',pw,lw),('tc',pt,lt),('et',pe,le)]:
                pn = pp.squeeze().cpu().numpy().astype(bool)
                ln = ll.squeeze().cpu().numpy().astype(bool)
                row[f'dice_{tag}'] = dice_score(
                    torch.from_numpy(pn.astype(np.float32)),
                    torch.from_numpy(ln.astype(np.float32)))
                row[f'hd95_{tag}'] = hausdorff_95(pn, ln)
                s, sp = sens_spec(pn.astype(float), ln.astype(float))
                row[f'sens_{tag}'] = s; row[f'spec_{tag}'] = sp
            rows.append(row)
    return pd.DataFrame(rows)

df = evaluate(model, test_loader)
df.to_csv(f'{OUT_DIR}/evaluation/results.csv', index=False)

print('\n' + '='*60)
print('BRATS-PEDs EVALUATION SUMMARY')
print('='*60)
for region, name in [('wt','Whole Tumor'),('tc','Tumor Core'),('et','Enhancing Tumor')]:
    print(f'\n  {name}:')
    print(f'    Dice : {df[f"dice_{region}"].mean():.4f} ± {df[f"dice_{region}"].std():.4f}')
    print(f'    HD95 : {df[f"hd95_{region}"].mean():.2f} mm')
    print(f'    Sens : {df[f"sens_{region}"].mean():.4f}')
    print(f'    Spec : {df[f"spec_{region}"].mean():.4f}')

import matplotlib.colors as mcolors

CMAP_COLORS = [(0,0,0,0),(1,.1,.1,.7),(.1,.1,1,.7),(0,1,1,.7),(1,1,0,.7)]
PED_CMAP    = mcolors.ListedColormap(CMAP_COLORS)

@torch.no_grad()
def visualise(model, loader, n=3):
    model.eval()
    for i, batch in enumerate(loader):
        if i >= n: break
        imgs   = batch['image'].to(DEVICE)
        labels = batch['label'].to(DEVICE)
        preds  = sliding_window_inference(imgs, ROI_SIZE, SW_BATCH, model, overlap=OVERLAP)

        pred_seg  = preds.argmax(1).squeeze().cpu().numpy()
        label_seg = labels.squeeze().cpu().numpy()
        flair     = imgs[0,3].cpu().numpy()     # T2-FLAIR channel

        mid = flair.shape[2]//2
        f_sl, p_sl, l_sl = flair[:,:,mid].T, pred_seg[:,:,mid].T, label_seg[:,:,mid].T

        fig, axes = plt.subplots(1,3, figsize=(15,5))
        fig.suptitle(f'Patient {i+1} — Axial Mid-Slice (T2-FLAIR)', fontsize=12)

        axes[0].imshow(f_sl, cmap='gray', origin='lower')
        axes[0].set_title('FLAIR Input')

        axes[1].imshow(f_sl, cmap='gray', origin='lower')
        axes[1].imshow(np.ma.masked_where(l_sl==0,l_sl),
                       cmap=PED_CMAP, vmin=0, vmax=4, alpha=0.7, origin='lower')
        axes[1].set_title('Ground Truth')

        axes[2].imshow(f_sl, cmap='gray', origin='lower')
        axes[2].imshow(np.ma.masked_where(p_sl==0,p_sl),
                       cmap=PED_CMAP, vmin=0, vmax=4, alpha=0.7, origin='lower')
        axes[2].set_title('Prediction')

        for ax in axes: ax.axis('off')

        from matplotlib.patches import Patch
        patches = [Patch(color=CMAP_COLORS[k][:3], label=LABEL_MAP[k], alpha=0.8)
                   for k in range(1,5)]
        axes[2].legend(handles=patches, loc='lower right', fontsize=7)

        plt.tight_layout()
        plt.savefig(f'{OUT_DIR}/evaluation/pred_sample_{i+1}.png', dpi=150, bbox_inches='tight')
        plt.show(); plt.close()

visualise(model, test_loader, n=3)
print('Visualisations saved')
